"""Agriculture-specific research policy for the CoScientist test branch.

The scientific rule is capability-aware, not molecule-phobic:
* unavailable wet-lab molecular work must never become a hidden requirement;
* public omics reanalysis is allowed and encouraged when provenance is explicit;
* hybrid studies may combine feasible new physiology with independent public omics;
* secondary data must never be represented as measurements generated by the authors.

This module is deliberately deterministic. The reasoning layer proposes a plan;
this policy layer decides whether the proposed execution route is admissible.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class AgricultureResearchMode(str, Enum):
    NEW_EXPERIMENT = "NEW_EXPERIMENT"
    PUBLIC_DATA = "PUBLIC_DATA"
    HYBRID = "HYBRID"


class PlanVerdict(str, Enum):
    PASS = "PASS"
    BLOCKED = "BLOCKED"
    DEFER = "DEFER"


@dataclass(frozen=True)
class MolecularPlan:
    """Minimal facts needed to enforce the molecular-evidence boundary."""

    mode: AgricultureResearchMode
    generates_new_molecular_measurements: bool = False
    uses_public_omics: bool = False
    wet_lab_explicitly_enabled: bool = False
    public_provenance_declared: bool = False
    public_accessions_declared: bool = False


@dataclass(frozen=True)
class MolecularPlanDecision:
    verdict: PlanVerdict
    reason: str
    public_omics_allowed: bool
    new_wet_lab_allowed: bool

    @property
    def allowed(self) -> bool:
        return self.verdict is PlanVerdict.PASS


def evaluate_molecular_plan(plan: MolecularPlan) -> MolecularPlanDecision:
    """Enforce the current agriculture CoScientist molecular-data policy.

    New qPCR/RNA-seq/etc. is not forbidden in principle; it is forbidden as an
    implicit requirement when the user has not explicitly enabled that wet-lab
    capability. Public omics is admissible only with explicit provenance and
    accession-level traceability.
    """
    if plan.generates_new_molecular_measurements and not plan.wet_lab_explicitly_enabled:
        return MolecularPlanDecision(
            verdict=PlanVerdict.BLOCKED,
            reason=(
                "plan requires new molecular measurements but wet-lab molecular "
                "capability was not explicitly enabled; redesign around feasible "
                "measurements or public omics"
            ),
            public_omics_allowed=bool(plan.uses_public_omics),
            new_wet_lab_allowed=False,
        )

    if plan.uses_public_omics and not plan.public_provenance_declared:
        return MolecularPlanDecision(
            verdict=PlanVerdict.BLOCKED,
            reason="public omics is proposed without an explicit provenance declaration",
            public_omics_allowed=False,
            new_wet_lab_allowed=bool(
                plan.generates_new_molecular_measurements and plan.wet_lab_explicitly_enabled
            ),
        )

    if plan.uses_public_omics and not plan.public_accessions_declared:
        return MolecularPlanDecision(
            verdict=PlanVerdict.BLOCKED,
            reason="public omics is proposed without accession-level source identifiers",
            public_omics_allowed=False,
            new_wet_lab_allowed=bool(
                plan.generates_new_molecular_measurements and plan.wet_lab_explicitly_enabled
            ),
        )

    if plan.mode is AgricultureResearchMode.PUBLIC_DATA and not plan.uses_public_omics:
        return MolecularPlanDecision(
            verdict=PlanVerdict.DEFER,
            reason="PUBLIC_DATA mode declares no public omics input; research mode is incomplete",
            public_omics_allowed=False,
            new_wet_lab_allowed=False,
        )

    return MolecularPlanDecision(
        verdict=PlanVerdict.PASS,
        reason=(
            "molecular evidence route is admissible: provenance boundary is explicit "
            "and no unavailable wet-lab work is silently required"
        ),
        public_omics_allowed=bool(plan.uses_public_omics),
        new_wet_lab_allowed=bool(
            plan.generates_new_molecular_measurements and plan.wet_lab_explicitly_enabled
        ),
    )
